### ISSUE TITLE
Removing unnecessary codes and settings + cleaning

### ISSUE THREAD

**Issue by arashmad** [FernLab/cookiecutter-fastapi-package#6]
**ToDo**:
- [x] Remove .env file.
- [x] Clean run.py file
- [x] Decrease docker size by add .dockerignore and decreasing layers
- [x] Clean env.py file
- [x] Clean config.ini file
- [x] ...
